In [5]:
import pandas as pd

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [6]:
df = pd.read_csv('covid_toy.csv')

In [7]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [10]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [13]:
X_train

    age  gender  fever   cough       city
48   66    Male   99.0  Strong  Bangalore
18   64  Female   98.0    Mild  Bangalore
57   49  Female   99.0  Strong  Bangalore
44   20    Male  102.0  Strong      Delhi
9    64  Female  101.0    Mild      Delhi
..  ...     ...    ...     ...        ...
74   34  Female  104.0  Strong      Delhi
11   65  Female   98.0    Mild     Mumbai
43   22  Female   99.0    Mild  Bangalore
71   75  Female  104.0  Strong      Delhi
84   69  Female   98.0  Strong     Mumbai

[80 rows x 5 columns]

In [14]:
from sklearn.compose import ColumnTransformer

In [15]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild', 'Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse_output=False, drop='first'),['gender','city'])
],remainder="passthrough")

In [16]:
transformer.fit_transform(X_train).shape

(80, 7)

In [18]:
transformer.transform(X_test).shape

(20, 7)